[functions.telemetry-api]
verify_jwt = false
entrypoint = "./functions/telemetry-api/index.ts"

[functions.telemetry-ingest]
verify_jwt = true
entrypoint = "./functions/telemetry-ingest/index.ts"

[functions.create-checkout]
verify_jwt = false
entrypoint = "./functions/create-checkout/index.ts"

[functions.stripe-webhook]
verify_jwt = false
entrypoint = "./functions/stripe-webhook/index.ts"
